// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9VCQHYdqXs2aSNEy1iyodwFtMW0JW2F8',
    appId: '1:471447579009:web:125830f648aa069ca3e080',
    messagingSenderId: '471447579009',
    projectId: 'hazy-flutter-fire-demo',
    authDomain: 'hazy-flutter-fire-demo.firebaseapp.com',
    storageBucket: 'hazy-flutter-fire-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIUM0EkG2PPfnHQ6i577tTZHJaW2OF298',
    appId: '1:471447579009:android:a35a1647ff3f5f4ba3e080',
    messagingSenderId: '471447579009',
    projectId: 'hazy-flutter-fire-demo',
    storageBucket: 'hazy-flutter-fire-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfWtSUZIMp77TW_qo0LhrFz4Wjuh1G5sM',
    appId: '1:471447579009:ios:65e70c4a7fad9966a3e080',
    messagingSenderId: '471447579009',
    projectId: 'hazy-flutter-fire-demo',
    storageBucket: 'hazy-flutter-fire-demo.appspot.com',
    iosClientId: '471447579009-kj163e97pcen8u5n4km4tbaedrbf5i7n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseDemo',
  );
}
